language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      script:
        - mkdir build
        - cd build
        - cmake -DSOCKET_CODE_COVERAGE=ON ..
        - make
        - test/libxio_test
        - bash <(curl -s https://codecov.io/bash)

    - os: osx
      osx_image: xcode8.2
      script:
        - mkdir build
        - cd build
        - cmake -G Xcode ..
        - xcodebuild -target libxio_test -project libxio.xcodeproj -configuration Release
        - test/Release/libxio_test